name: K6 Tests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  k6_load_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
      - name: Instalar k6
        run: curl https://github.com/grafana/k6/releases/download/v0.45.0/k6-v0.45.0-linux-arm64.tar.gz -L
             npm install ./k6
      - name: Run K6 tests
        run: k6 run index.js --vus 20 --duration 30s